name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build static files
        run: |
          # Add your build commands here
          # For example, if using npm:
          npm install
          npm run build

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'  # Adjust this path to your build output directory

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2 